import { Scale, ShieldAlert, Signpost, Sparkles, Tag } from "lucide-react";

import { SeverityMeter, type SeverityValue } from "@/components/case/severity-badge";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";

export type AiAnalysisView = {
  readonly summary: string;
  readonly suggestedCategory: string;
  readonly severity: SeverityValue;
  readonly severityReason: string;
  readonly reportingDirection: string;
  readonly immediateSafetyGuidance: string | null;
  readonly potentiallyRelevantRegulatoryContext: string | null;
  readonly modelLabel: string;
};

function Field({
  icon: Icon,
  label,
  children,
}: {
  readonly icon: typeof Tag;
  readonly label: string;
  readonly children: React.ReactNode;
}) {
  return (
    <div className="space-y-1.5">
      <h4 className="flex items-center gap-1.5 text-xs font-semibold tracking-wide text-muted-foreground uppercase">
        <Icon aria-hidden="true" className="size-3.5" />
        {label}
      </h4>
      <p className="text-sm leading-relaxed whitespace-pre-wrap">{children}</p>
    </div>
  );
}

/**
 * Presentation of an AI-assisted analysis, shared by the report wizard's review
 * step and the saved case page so both render identically.
 *
 * Every label says "suggested" or "AI-assisted". Nothing here is presented as a
 * decision, and the provenance line names the model that produced it
 * (Docs/11-UI-UX.md §13). The reporting direction gets the most visual weight
 * because it is the one thing a citizen leaves with that they did not arrive
 * with.
 */
export function AiAnalysisCard({ analysis }: { readonly analysis: AiAnalysisView }) {
  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-center gap-2.5">
        <span className="flex size-8 shrink-0 items-center justify-center rounded-lg bg-primary/10 text-primary">
          <Sparkles aria-hidden="true" className="size-4" />
        </span>
        <h3 className="text-sm font-semibold tracking-wide uppercase">
          AI-assisted summary
        </h3>
        <Badge variant="outline">Suggestion, not a decision</Badge>
      </div>

      <p className="text-[0.9375rem] leading-relaxed whitespace-pre-wrap">
        {analysis.summary}
      </p>

      <div className="rounded-xl border border-border bg-muted/50 p-4">
        <SeverityMeter severity={analysis.severity} />
      </div>

      <div className="grid gap-5 sm:grid-cols-2">
        <Field icon={Scale} label="Why this severity">
          {analysis.severityReason}
        </Field>
        <Field icon={Tag} label="Suggested category">
          {analysis.suggestedCategory}
        </Field>
      </div>

      <div className="rounded-xl border border-primary/20 bg-primary/[0.05] p-4">
        <h4 className="flex items-center gap-1.5 text-xs font-semibold tracking-wide text-primary uppercase">
          <Signpost aria-hidden="true" className="size-3.5" />
          Suggested reporting direction
        </h4>
        <p className="mt-1.5 text-[0.9375rem] leading-relaxed font-medium whitespace-pre-wrap">
          {analysis.reportingDirection}
        </p>
      </div>

      {analysis.immediateSafetyGuidance ? (
        <Alert variant="destructive">
          <ShieldAlert />
          <AlertTitle>If you may be at risk</AlertTitle>
          <AlertDescription>
            {analysis.immediateSafetyGuidance}
            <span className="mt-1.5 block">
              CivicProof is not an emergency service and cannot send help.
            </span>
          </AlertDescription>
        </Alert>
      ) : null}

      {analysis.potentiallyRelevantRegulatoryContext ? (
        <div className="rounded-xl border border-border bg-muted/40 p-4">
          <Field icon={Scale} label="Potentially relevant context">
            {analysis.potentiallyRelevantRegulatoryContext}
          </Field>
          <p className="mt-2 text-xs leading-relaxed text-muted-foreground">
            General context only — not legal advice, and not a determination that
            any rule was broken.
          </p>
        </div>
      ) : null}

      <Separator />

      <p className="text-xs leading-relaxed text-muted-foreground">
        Generated by{" "}
        <span className="font-mono text-[0.6875rem]">{analysis.modelLabel}</span>{" "}
        from the information you provided. These are suggestions to help you
        decide what to do next — not an official assessment, and not a finding
        about any person. Nothing has been sent to any authority.
      </p>
    </div>
  );
}
