import { z } from "zod";

import {
  applicationSubmitterInput,
  runApplicationSubmitter,
} from "@/lib/tools/application-submitter";
import { eligibilityCheckerInput, runEligibilityChecker } from "@/lib/tools/eligibility-checker";
import { formFillerInput, runFormFiller } from "@/lib/tools/form-filler";
import { schemeMatcherInput, runSchemeMatcher } from "@/lib/tools/scheme-matcher";
import { statusTrackerInput, runStatusTracker } from "@/lib/tools/status-tracker";
import { toolError, type ToolContext, type ToolResult } from "@/lib/tools/types";

/**
 * The tool registry.
 *
 * One place defines each tool's name, description, argument schema and handler,
 * so the schema the model is shown and the schema its arguments are validated
 * against are the same object. They cannot drift.
 *
 * Every handler receives a server-built ToolContext. Nothing identifying the
 * citizen appears in any model-facing schema.
 */

type Handler = (args: never, context: ToolContext) => Promise<ToolResult<unknown>>;

type ToolSpec = {
  readonly name: string;
  readonly description: string;
  readonly schema: z.ZodType;
  readonly handler: Handler;
};

export const TOOL_SPECS: readonly ToolSpec[] = [
  {
    name: "match_schemes",
    description:
      "List every welfare scheme Sahayak supports. Call this first, before discussing any scheme. Never mention a scheme that is not in the result.",
    schema: schemeMatcherInput,
    handler: runSchemeMatcher as Handler,
  },
  {
    name: "check_eligibility",
    description:
      "Evaluate the citizen's facts against a scheme's official stored rules. This is the ONLY way to decide eligibility — never judge it yourself. Pass only facts the citizen actually stated.",
    schema: eligibilityCheckerInput,
    handler: runEligibilityChecker as Handler,
  },
  {
    name: "prepare_application",
    description:
      "Prepare a draft application once eligibility is LIKELY_ELIGIBLE. Produces a draft for the citizen to review. Submits nothing.",
    schema: formFillerInput,
    handler: runFormFiller as Handler,
  },
  {
    name: "submit_application",
    description:
      "Record the simulated submission and return a tracking ID. Only succeeds after the citizen has pressed the confirm button. Never claim a submission happened unless this returns ok.",
    schema: applicationSubmitterInput,
    handler: runApplicationSubmitter as Handler,
  },
  {
    name: "get_application_status",
    description:
      "Look up the stored status of a submitted application. Never state a status that did not come from this tool.",
    schema: statusTrackerInput,
    handler: runStatusTracker as Handler,
  },
];

/** JSON Schema for one tool, in the shape the chat-completions API expects. */
function toFunctionSchema(spec: ToolSpec): Record<string, unknown> {
  const jsonSchema = z.toJSONSchema(spec.schema, { io: "input" }) as Record<string, unknown>;

  // The generated document carries a $schema banner the API has no use for.
  const parameters = Object.fromEntries(
    Object.entries(jsonSchema).filter(([key]) => key !== "$schema"),
  );

  return {
    type: "function",
    function: {
      name: spec.name,
      description: spec.description,
      parameters,
    },
  };
}

/** Tool definitions sent with every request. Stable order keeps the prefix cacheable. */
export const TOOL_DEFINITIONS: readonly Record<string, unknown>[] =
  TOOL_SPECS.map(toFunctionSchema);

export const TOOL_NAMES: readonly string[] = TOOL_SPECS.map((spec) => spec.name);

/**
 * Validate and run one tool call.
 *
 * Arguments arrive as a JSON string generated by the model, so both the parse
 * and the schema check can fail. Neither throws: the model gets a readable
 * error and another turn to correct itself, which is far more useful than an
 * exception unwinding the request.
 */
export async function executeTool(
  name: string,
  rawArguments: string,
  context: ToolContext,
): Promise<ToolResult<unknown>> {
  const spec = TOOL_SPECS.find((candidate) => candidate.name === name);

  if (!spec) {
    return toolError("INVALID_INPUT", `There is no tool called "${name}".`);
  }

  let parsed: unknown;

  try {
    parsed = rawArguments.trim().length === 0 ? {} : JSON.parse(rawArguments);
  } catch {
    return toolError("INVALID_INPUT", `Arguments for "${name}" were not valid JSON.`);
  }

  const validated = spec.schema.safeParse(parsed);

  if (!validated.success) {
    const detail = validated.error.issues
      .map((issue) => `${issue.path.join(".") || "(root)"}: ${issue.message}`)
      .join("; ");

    return toolError("INVALID_INPUT", `Arguments for "${name}" are invalid — ${detail}`);
  }

  return spec.handler(validated.data as never, context);
}
